import Head from "next/head";
import { Inter } from "next/font/google";
import SideBar from "@/components/SideBar";
import Header from "@/components/Header";
import SavingsCard from "@/components/SavingsCard";
import TransactionDetails from "@/components/TransactionDetails";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex w-full">
        <SideBar />
        <div className="flex-1 w-full dark:bg-black bg-[#E7E9EF]">
          {/** Header */}
          <Header />

          {/** cards */}
          <div className="grid grid-cols-3 mx-[40px] mt-16 items-center gap-5">
            <SavingsCard />
            <SavingsCard />
            <SavingsCard />
          </div>

          {/* transactions */}
          <div className="mx-[40px] mt-16">
            <TransactionDetails />
          </div>
        </div>
      </main>
    </>
  );
}
