import Header from '@/components/Header'
import SideBar from '@/components/SideBar'
import Head from 'next/head'
import React from 'react'
import { AiFillQuestionCircle } from 'react-icons/ai'

export default function savings() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex w-full">
        <SideBar />
        <div className="flex-1 w-full dark:bg-black bg-[#E7E9EF]">
          {/** Header */}
          <Header />

        <div className='fixed right-16 bottom-20'>
        <AiFillQuestionCircle size={60} color='#6C757D' />
        </div>
        </div>
      </main>
    </div>
  )
}
